// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrsOl7gfW8w0nBiI_YMoICUKsDSxvxrjo',
    appId: '1:260639478079:web:f60e898757e7881e83838a',
    messagingSenderId: '260639478079',
    projectId: 'examen-final-mendoza',
    authDomain: 'examen-final-mendoza.firebaseapp.com',
    storageBucket: 'examen-final-mendoza.firebasestorage.app',
    measurementId: 'G-WQEGT4ZVJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0eE-gyiOCXbX9Uz6EjItdCqddv8DWZdo',
    appId: '1:260639478079:android:812c1a129c67eb8783838a',
    messagingSenderId: '260639478079',
    projectId: 'examen-final-mendoza',
    storageBucket: 'examen-final-mendoza.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAajOaMQLeOcQwpwK1J5PhfxmBmizZHENs',
    appId: '1:260639478079:ios:cb9e7fc562f3c6df83838a',
    messagingSenderId: '260639478079',
    projectId: 'examen-final-mendoza',
    storageBucket: 'examen-final-mendoza.firebasestorage.app',
    iosBundleId: 'com.example.examenFinalMendoza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAajOaMQLeOcQwpwK1J5PhfxmBmizZHENs',
    appId: '1:260639478079:ios:cb9e7fc562f3c6df83838a',
    messagingSenderId: '260639478079',
    projectId: 'examen-final-mendoza',
    storageBucket: 'examen-final-mendoza.firebasestorage.app',
    iosBundleId: 'com.example.examenFinalMendoza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrsOl7gfW8w0nBiI_YMoICUKsDSxvxrjo',
    appId: '1:260639478079:web:55e06f526c5a379083838a',
    messagingSenderId: '260639478079',
    projectId: 'examen-final-mendoza',
    authDomain: 'examen-final-mendoza.firebaseapp.com',
    storageBucket: 'examen-final-mendoza.firebasestorage.app',
    measurementId: 'G-MRM597G16P',
  );
}
